### ISSUE TITLE
VMPC keyboard screen (`Shift + 0` > `F2`) does not respond to key presses

### ISSUE THREAD

**Issue by ShoveD01** [izzyreal/mpc#251] opened 2024-10-24 07:36 UTC
The keyboard learn is not working in the iOS version. In fact the keyboard doesn’t respond to any external keyboard presses when in the keyboard configure page, according to the manual f1 to f6 and up/down should work, but they don’t.

**Comment by izzyreal** [comment] 2024-10-24 08:29
Thanks for the report @ShoveD01. Good find! I've reproduced the issue, and found the cause. It's because of a series of bogus entries in https://github.com/izzyreal/mpc/blob/7c482e10acff19f9d4eebc60afe095f6a0893626/src/main/controls/KeyCodes.hpp#L364

I will try to push a fix to TestFlight asap.

**Comment by izzyreal** [comment] 2024-10-24 11:35
Resolved in 7659ba7.

**Closed by izzyreal** 2024-10-24 11:35 UTC

**Comment by izzyreal** [comment] 2024-10-27 22:13
Fix is part of https://github.com/izzyreal/vmpc-juce/releases/tag/v0.6.4. Should appear in TestFlight as soon as the build is approved by Apple (usually within a day or so).

**Comment by ShoveD01** [comment] 2024-10-30 08:03
The keyboard screen now working perfectly thanksSent from my iPadOn 27 Oct 2024, at 22:14, Izmar Verhage ***@***.***> wrote:﻿
Fix is part of https://github.com/izzyreal/vmpc-juce/releases/tag/v0.6.4. Should appear in TestFlight as soon as the build is approved by Apple (usually within a day or so).
